/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminTabPackages;

import AdminTabPackages.mealManagementPackage.AddBazarAmount;
import AdminTabPackages.mealManagementPackage.GenerateDueTableOfAMonth;
import AdminTabPackages.mealManagementPackage.ShowStudentsMealData;
import AdminTabPackages.mealManagementPackage.ViewStudentDueTable;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Tahmid
 */
public class MealManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form MealManagementPanel
     */
    public MealManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewStudentMealData = new javax.swing.JButton();
        generateDueTablebutton = new javax.swing.JButton();
        showDueTableButton = new javax.swing.JButton();
        addBazarAmountButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(692, 390));

        viewStudentMealData.setText("Veiw Students Meal Data");
        viewStudentMealData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentMealDataActionPerformed(evt);
            }
        });

        generateDueTablebutton.setText("Generate Due Table Of A Month");
        generateDueTablebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDueTablebuttonActionPerformed(evt);
            }
        });

        showDueTableButton.setText("Show Due Table");
        showDueTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDueTableButtonActionPerformed(evt);
            }
        });

        addBazarAmountButton.setText("Add Bazar Amount");
        addBazarAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBazarAmountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBazarAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewStudentMealData, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateDueTablebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDueTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(addBazarAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewStudentMealData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generateDueTablebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showDueTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateDueTablebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDueTablebuttonActionPerformed
        // TODO add your handling code here:
        GenerateDueTableOfAMonth frame = new GenerateDueTableOfAMonth();
        openFrame(frame);
        
    }//GEN-LAST:event_generateDueTablebuttonActionPerformed

    private void viewStudentMealDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentMealDataActionPerformed
        // TODO add your handling code here:
       ShowStudentsMealData frame = new ShowStudentsMealData();
        openFrame(frame);
    }//GEN-LAST:event_viewStudentMealDataActionPerformed

    private void showDueTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDueTableButtonActionPerformed
        // TODO add your handling code here:
       ViewStudentDueTable frame =  new ViewStudentDueTable();
        openFrame(frame);
    }//GEN-LAST:event_showDueTableButtonActionPerformed

    private void addBazarAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBazarAmountButtonActionPerformed
        // TODO add your handling code here:
        AddBazarAmount frame = new AddBazarAmount();
        openFrame(frame);
    }//GEN-LAST:event_addBazarAmountButtonActionPerformed
    public void openFrame(JFrame frame){
         frame.setVisible(true);
            frame.setResizable(false);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (int) ((dim.getWidth() - frame.getWidth()) / 2);
            int y = 100;
            frame.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBazarAmountButton;
    private javax.swing.JButton generateDueTablebutton;
    private javax.swing.JButton showDueTableButton;
    private javax.swing.JButton viewStudentMealData;
    // End of variables declaration//GEN-END:variables
}
