/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminTabPackages;

import AdminTabPackages.mealManagementPackage.GenerateDueTableOfAMonth;

/**
 *
 * @author Tahmid
 */
public class MealManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form MealManagementPanel
     */
    public MealManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewStudentMealData = new javax.swing.JButton();
        generateDueTablebutton = new javax.swing.JButton();
        showDueTableButton = new javax.swing.JButton();

        viewStudentMealData.setText("Veiw Students Meal Data");

        generateDueTablebutton.setText("Generate Due Table Of A Month");
        generateDueTablebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDueTablebuttonActionPerformed(evt);
            }
        });

        showDueTableButton.setText("Show Due Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showDueTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateDueTablebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewStudentMealData, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(viewStudentMealData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(generateDueTablebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(showDueTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateDueTablebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDueTablebuttonActionPerformed
        // TODO add your handling code here:
        GenerateDueTableOfAMonth frame = new GenerateDueTableOfAMonth();
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_generateDueTablebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateDueTablebutton;
    private javax.swing.JButton showDueTableButton;
    private javax.swing.JButton viewStudentMealData;
    // End of variables declaration//GEN-END:variables
}
