/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package allpanels;

import AdminTabPackages.HallInformationPanel;
import java.awt.CardLayout;

/**
 *
 * @author Siyam
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    MainFrame parentFrame = null;
    HallInformationPanel hallInformationPanel = new HallInformationPanel();
    CardLayout cardLayoutForHallInformationTab = new CardLayout();
    
    public AdminPanel() {
        initComponents();
    }
    
    /**
     * this constructor is used to set the parentFrame reference 
     * so that after log out it can show it's parent frome
     * @param parent 
     */
    public AdminPanel(MainFrame parent) {
        initComponents();
        this.parentFrame = parent;
        setHallInformationTab();
    }
    
    void setHallInformationTab(){
      hallInformationPanelContainer.setLayout(cardLayoutForHallInformationTab);
      hallInformationPanelContainer.add("HallInformationPanel",hallInformationPanel);
      cardLayoutForHallInformationTab.show(hallInformationPanelContainer, "HallInformationPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainAdminTabPanel = new javax.swing.JTabbedPane();
        mealManagementTabPanel = new javax.swing.JPanel();
        checkInCheckOutTabPanel = new javax.swing.JPanel();
        studentManagementTabPanel = new javax.swing.JPanel();
        adminOptionsTabPanel = new javax.swing.JPanel();
        hallInformationTabPanel = new javax.swing.JPanel();
        hallInformationPanelContainer = new javax.swing.JPanel();
        adminInformationLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();

        javax.swing.GroupLayout mealManagementTabPanelLayout = new javax.swing.GroupLayout(mealManagementTabPanel);
        mealManagementTabPanel.setLayout(mealManagementTabPanelLayout);
        mealManagementTabPanelLayout.setHorizontalGroup(
            mealManagementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        mealManagementTabPanelLayout.setVerticalGroup(
            mealManagementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        mainAdminTabPanel.addTab("Meal Management", mealManagementTabPanel);

        javax.swing.GroupLayout checkInCheckOutTabPanelLayout = new javax.swing.GroupLayout(checkInCheckOutTabPanel);
        checkInCheckOutTabPanel.setLayout(checkInCheckOutTabPanelLayout);
        checkInCheckOutTabPanelLayout.setHorizontalGroup(
            checkInCheckOutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        checkInCheckOutTabPanelLayout.setVerticalGroup(
            checkInCheckOutTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        mainAdminTabPanel.addTab("Check in Check out", checkInCheckOutTabPanel);

        javax.swing.GroupLayout studentManagementTabPanelLayout = new javax.swing.GroupLayout(studentManagementTabPanel);
        studentManagementTabPanel.setLayout(studentManagementTabPanelLayout);
        studentManagementTabPanelLayout.setHorizontalGroup(
            studentManagementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        studentManagementTabPanelLayout.setVerticalGroup(
            studentManagementTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        mainAdminTabPanel.addTab("Student Management", studentManagementTabPanel);

        javax.swing.GroupLayout adminOptionsTabPanelLayout = new javax.swing.GroupLayout(adminOptionsTabPanel);
        adminOptionsTabPanel.setLayout(adminOptionsTabPanelLayout);
        adminOptionsTabPanelLayout.setHorizontalGroup(
            adminOptionsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        adminOptionsTabPanelLayout.setVerticalGroup(
            adminOptionsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        mainAdminTabPanel.addTab("Admin Options", adminOptionsTabPanel);

        javax.swing.GroupLayout hallInformationPanelContainerLayout = new javax.swing.GroupLayout(hallInformationPanelContainer);
        hallInformationPanelContainer.setLayout(hallInformationPanelContainerLayout);
        hallInformationPanelContainerLayout.setHorizontalGroup(
            hallInformationPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        hallInformationPanelContainerLayout.setVerticalGroup(
            hallInformationPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hallInformationTabPanelLayout = new javax.swing.GroupLayout(hallInformationTabPanel);
        hallInformationTabPanel.setLayout(hallInformationTabPanelLayout);
        hallInformationTabPanelLayout.setHorizontalGroup(
            hallInformationTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hallInformationPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hallInformationTabPanelLayout.setVerticalGroup(
            hallInformationTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hallInformationTabPanelLayout.createSequentialGroup()
                .addComponent(hallInformationPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        mainAdminTabPanel.addTab("Hall Information", hallInformationTabPanel);

        adminInformationLabel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        adminInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInformationLabel.setText("Admin Information Panel");

        logOutButton.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainAdminTabPanel)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(adminInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminInformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(logOutButton))
                .addGap(18, 18, 18)
                .addComponent(mainAdminTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setAdminInformationLabel(String name) {
        adminInformationLabel.setText("Logged In As: " + name + " [Admin]");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminInformationLabel;
    private javax.swing.JPanel adminOptionsTabPanel;
    private javax.swing.JPanel checkInCheckOutTabPanel;
    private javax.swing.JPanel hallInformationPanelContainer;
    private javax.swing.JPanel hallInformationTabPanel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTabbedPane mainAdminTabPanel;
    private javax.swing.JPanel mealManagementTabPanel;
    private javax.swing.JPanel studentManagementTabPanel;
    // End of variables declaration//GEN-END:variables
}
