/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package allpanels;

import java.awt.Button;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import dbconnection.CreateConnection;
import diningmanager.DiningManagerPanel;
import extra.Pair;
import gatekeeper.*;

/**
 *
 * @author Siyam
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogInFrame
     */
    CardLayout cardLayout = null;
    LogInPanel loginPanel = null;
    AdminPanel adminPanel = null;
    GateKeeperPanel gateKeeperPanel = null;
    DiningManagerPanel dinigManagerPanel = null;
    
    public MainFrame() {
        super("Universal Hall Management System  1.2");
        initComponents();
        readyAllPanels();
        makeCardLayoutReady();
        
    }
    
    void readyAllPanels(){
        loginPanel = new LogInPanel(this);
        adminPanel = new AdminPanel(this);
        gateKeeperPanel = new GateKeeperPanel(this);
        dinigManagerPanel = new DiningManagerPanel(this);
    }
    void makeCardLayoutReady(){
        cardLayout = new CardLayout();
        panelContainer.setLayout(cardLayout);
        panelContainer.add("LogInPanel",loginPanel);
        panelContainer.add("AdminPanel",adminPanel);
        panelContainer.add("GateKeeperPanel",gateKeeperPanel);
        panelContainer.add("DinigManagerPanel",dinigManagerPanel);
        //logOutButton.setVisible(false);
        goLoginPanel();
    }
    
   public void goLoginPanel(){
        cardLayout.show(panelContainer, "LogInPanel");
      //  loggedInAsLabel.setText("Universal Hall Management System");
     //   logOutButton.setVisible(false);
     
    }
   
   public void goAdminPanel(String userName){
     //  System.out.println("hello wold");
       cardLayout.show(panelContainer, "AdminPanel");
       adminPanel.setUserInformationLabel(userName);
   }
   
   public void goGateKeeperPanel(String userName){
       
       cardLayout.show(panelContainer, "GateKeeperPanel");
       gateKeeperPanel.setUserInformationLabel(userName);
       
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        panelContainerLayout.setVerticalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContainer;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelContainer(){
        return this.panelContainer;
    }
    
    public JPanel getAdminPanel(){
        return adminPanel;
    }

    void goDiningManagerPanel(String string) {
       cardLayout.show(panelContainer,"DinigManagerPanel");
       dinigManagerPanel.setUserInformationLabel(string);
    
    }
    
    /**
    public JButton getLogOutButton(){
       return this.logOutButton;
    }
    public JLabel getSignedInAsText(){
        return this.loggedInAsLabel;
    }
    * 
    */
}
