/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gatekeeper;

import allpanels.MainFrame;
import dbconnection.CreateConnection;
import extra.Pair;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Siyam
 */
public class GateKeeperPanel extends javax.swing.JPanel {

    /**
     * Creates new form GateKeeper
     */
    private MainFrame mainFrame;

    public GateKeeperPanel() {
        initComponents();
    }

    public GateKeeperPanel(MainFrame mainFrame) {

        initComponents();
        this.mainFrame = mainFrame;
        checkInButton.setEnabled(false);
        checkOutButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        ViewInfoTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        getRegNoTextField = new java.awt.TextField();
        checkInButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchInEntryView = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        logOutButton = new javax.swing.JButton();
        loggedInAsLabel = new javax.swing.JLabel();

        label1.setText("label1");

        ViewInfoTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ViewInfoTabStateChanged(evt);
            }
        });

        jLabel2.setText("Enter Reg No :");

        getRegNoTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getRegNoTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getRegNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRegNoTextFieldActionPerformed(evt);
            }
        });

        checkInButton.setText("CHECK IN");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        checkOutButton.setText("CHECK OUT");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Name : ");

        studentName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(checkInButton)
                        .addGap(107, 107, 107)
                        .addComponent(checkOutButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(getRegNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getRegNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInButton)
                    .addComponent(checkOutButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ViewInfoTab.addTab("Data Entry", jPanel2);

        jLabel1.setText("Search By Reg. No :  ");

        SearchInEntryView.setToolTipText("Enter Registration Number");
        SearchInEntryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchInEntryViewActionPerformed(evt);
            }
        });

        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(logTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchInEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(refreshButton)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchInEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        ViewInfoTab.addTab("View Entry", jPanel1);

        logOutButton.setText("LogOut");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        loggedInAsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loggedInAsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedInAsLabel.setText("user name");
        loggedInAsLabel.setToolTipText("");
        loggedInAsLabel.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewInfoTab)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedInAsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101)
                        .addComponent(logOutButton)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedInAsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(logOutButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        mainFrame.goLoginPanel();

    }//GEN-LAST:event_logOutButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:

        CreateConnection.insertDatatoDatabase("insert into check_in_out(id,`type`) VALUES(" + regNo + ",'OUT')");
        checkOutButton.setEnabled(false);
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void getRegNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRegNoTextFieldActionPerformed
        // TODO add your handling code here:
        regNo = evt.getActionCommand();
        System.out.println(regNo);
        if (regNo.length() != 10) {
            JOptionPane.showMessageDialog(this, "Incorrect Registration No Format", "Error!", WIDTH);
            return;
        }
        checkInButton.setEnabled(true);
        checkOutButton.setEnabled(true);
        try {
            resultSet = CreateConnection.getResultFromDatabase("select student_name from student_info where id=" + regNo + "");
            if (resultSet.next()) {
                studentName.setText(resultSet.getString("student_name"));
            } else {
                studentName.setText("Student Not Found On DataBase");
                checkInButton.setEnabled(false);
                checkOutButton.setEnabled(false);
            }

            resultSet = CreateConnection.getResultFromDatabase("select `type` from check_in_out where day_time = (select max(day_time) from check_in_out where id=" + regNo + ")");
            resultSet.next();
            String type = resultSet.getString("type");
            if (type.equals("IN")) {
                checkInButton.setEnabled(false);
            } else {
                checkOutButton.setEnabled(false);
            }
        } catch (SQLException ex) {

            checkOutButton.setEnabled(false);
            checkInButton.setEnabled(true);
            //  Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            // Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_getRegNoTextFieldActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        // TODO add your handling code here:
        CreateConnection.insertDatatoDatabase("insert into check_in_out(id) VALUES(" + regNo + ")");
        checkInButton.setEnabled(false);
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        refreshButtonPressed();

    }//GEN-LAST:event_refreshButtonActionPerformed

    public void refreshButtonPressed() {

        try {
            // TODO add your handling code here:
            resultSet = CreateConnection.getResultFromDatabase("select * from check_in_out ORDER BY DAY_TIME DESC");
            logTable.setModel(TableModelGateKeeperViewEntry.resultSetToTableModel(resultSet));
        } catch (ClassNotFoundException ex) {
            //  Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            //  Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void SearchInEntryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchInEntryViewActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            resultSet = CreateConnection.getResultFromDatabase("select * from check_in_out WHERE id = " + SearchInEntryView.getText() + " ORDER BY DAY_TIME DESC");
            logTable.setModel(TableModelGateKeeperViewEntry.resultSetToTableModel(resultSet));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GateKeeperPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SearchInEntryViewActionPerformed

    private void ViewInfoTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ViewInfoTabStateChanged
        // TODO add your handling code here:
        if (logTable.getRowCount() == 0) {
            refreshButtonPressed();
        }
    }//GEN-LAST:event_ViewInfoTabStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchInEntryView;
    private javax.swing.JTabbedPane ViewInfoTab;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private java.awt.TextField getRegNoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTable logTable;
    private javax.swing.JLabel loggedInAsLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables

    private ResultSet resultSet;
    private ResultSetMetaData resultSetMetaData;
    Pair<ResultSet, ResultSetMetaData> results = null;
    public String regNo;

    public void setUserInformationLabel(String userName) {
        loggedInAsLabel.setText("Logged In As: " + userName + " [GateKeeper]");

    }
}
